import {{ root_package }}.core.model.{{ ProjectPrefix }}Model
import {{ root_package }}.grpc.{{ ProjectPrefix }}Level
global {{ root_package }}.core.model.{{ ProjectPrefix }}Assessment {{ ProjectPrefix }}Assessment;
dialect  "mvel"

rule "Calculate Fraud Risk - Scenario 1"
    when
        {{ projectPrefix }}Model:{{ ProjectPrefix }}Model(attempts > 10 && attempts < 100);
    then
      	{{ ProjectPrefix }}Assessment.setLevel({{ ProjectPrefix }}Level.{{ PROJECT_PREFIX }}_MEDIUM);
end